spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode : always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_LOCAL_PORT}/${DB_LOCAL_DATABASE}?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: ${DB_LOCAL_USERNAME}
    password: ${DB_LOCAL_PASSWORD}


aws:
  region: ap-northeast-2 #asia/seoul
  s3:
    bucket: maidlab-bucket
    access-key: ${AWS_S3_ACCESSKEY}
    secret-key: ${AWS_S3_SECRETKEY}


