spring:
  profiles:
    group:
      local: "local,localkey,swagger"
      prod: "prod, localkey, swagger"
    active: prod

# 알림 설정
notification:
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL:}

